# This is a basic workflow to help you get started with Actions

name: Push-To-EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: Deploy to EC2 on Main Branch Push
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/test
          remote_host: ec2-54-74-194-122.eu-west-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.AWS_PRIVATE_KEY }}"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-74-194-122.eu-west-1.compute.amazonaws.com
          username: ubuntu
          key: "${{ secrets.AWS_PRIVATE_KEY }}"
          script: gunicorn -b 127.0.0.1:8080 ~/deployedApp/wsgi &
