# This workflow, automatically deploys new changes to the ec2 instance

name: Push-To-EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on every push made to the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: Deploy to EC2 on Main Branch Push
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # SSH into the ec2 instance
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ec2-34-246-248-234.eu-west-1.compute.amazonaws.com
          username: ubuntu
          key: "${{ secrets.AWS_PRIVATE_KEY }}"
          script: |
            cd ~/FarmTrac
            git pull
            cd ~
            bash startServer.sh
